# Generated by Django 3.2 on 2022-01-12 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20211216_2355'),
        ('fantasy', '0002_userfplpick_gameweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='att1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_att1', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='att2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_att2', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='att3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_att3', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='att4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_att4', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='def1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_def1', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='def2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_def2', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='def3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_def3', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='def4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_def4', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='def5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_def5', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='gkp1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_gkp1', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='gkp2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_gkp2', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='mid1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_mid1', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='mid2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_mid2', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='mid3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_mid3', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplcreate',
            name='mid4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpl_create_mid4', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='att1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att1', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='att2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att2', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='att3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att3', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='att_bench',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_bench', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='def1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='def1', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='def2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='def2', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='def3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='def3', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='def4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='def4', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='def_bench',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='def_bench', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='gkp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gkp', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='gkp_bench',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gkp_bench', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='mid1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid1', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='mid2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid2', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='mid3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid3', to='league.player'),
        ),
        migrations.AlterField(
            model_name='userfplpick',
            name='mid_bench',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid_bench', to='league.player'),
        ),
    ]
