# Generated by Django 3.2 on 2021-11-19 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.PositiveIntegerField(default=0)),
                ('away_team_score', models.PositiveIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameweekName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('name_short', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('ga', models.PositiveIntegerField(default=0)),
                ('gf', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_goal_scored', models.PositiveIntegerField(default=0)),
                ('total_assists', models.PositiveIntegerField(default=0)),
                ('sfl_price', models.PositiveIntegerField(default=0)),
                ('sfl_gw_point', models.PositiveIntegerField(default=0)),
                ('sfl_total_points', models.PositiveIntegerField(default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameweekFixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fx1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_1', to='league.fixture')),
                ('fx2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_2', to='league.fixture')),
                ('gw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameweek', to='league.gameweekname')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='league.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='league.team'),
        ),
    ]
