# Generated by Django 3.2 on 2023-03-19 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20211216_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweekfixtures',
            name='fx3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_3', to='league.fixture'),
        ),
    ]
